export const allColors = {
  schwarz: 'black',
  blau: 'blue',
  rot: 'red',
  gruen: 'green',
  weiss: 'white',
  pink: 'pink',
  mischfarben: 'linear-gradient(to bottom, #33ccff 0%, #ff66ff 100%)',
  beige: '#F5F5DC',
  grau: '#808080',
  braun: 'brown',
  gelb: 'yellow',
  orange: 'orange',
  lila: 'purple',
  silver: '#C0C0C0',
  gold: '#FFD700',
  bronze: '#cd7f32',
  transparent: 'white',
};
